### ISSUE TITLE
wrong effective time overlap or bad output message

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#20]
For one of my stations, stationxml here:
http://files.anss-sis.scsn.org/production/FDSNstationXML/CO/CO_CSB.xml

I got this error, which goes on for a couple of pages, trimmed for bug post. I am not sure if the overlap calculation is right, I don't think I have overlapping channels, but at a minimum the output of this error message is way too verbose to be helpful. Probably don't need to print all of the channels, just the two that supposedly overlap.

CO_CSB.xml|252|[[Channel [code=EH1, locationCode=00, startDate=Sun Apr 12 20:00:00 EDT 2009, endDate=Thu Sep 03 12:00:00 EDT 2009], Channel [code=EH1, locationCode=00, startDate=Thu Sep 03 12:00:00 EDT 2009, endDate=Wed Sep 09 12:00:00 EDT 2009], Channel [code=EH1, locationCode=00, startDate=Wed Sep 09 12:00:00 EDT 2009, endDate=Mon Dec 14 11:00:00 EST 2009],
<snip>
Channel [code=VMV, locationCode=01, startDate=Thu Feb 11 18:00:00 EST 2016, endDate=Thu Mar 24 12:00:00 EDT 2016], Channel [code=VMW, locationCode=00, startDate=Wed Apr 27 14:00:00 EDT 2016, endDate=null], Channel [code=VMW, locationCode=01, startDate=Thu Feb 11 18:00:00 EST 2016, endDate=Thu Mar 24 12:00:00 EDT 2016]]] Channel epoch overlap not allowed|CO|||CSB|2009-04-13T00:00:00|||||

**Comment by metempleton** [comment]
To elaborate on this a bit, I broke one of the messages up so that I could 
read it.  There are overlap messages for (nearly?) every channel epoch in 
this station file.  For CI.DSN6.60.BHE only, the channel epochs from the 
XML file read:

      <fsx:Channel code="BHE" startDate="2012-11-02T00:00:00Z" endDate="2013-02-07T21:00:00Z" locationCode="60">
      <fsx:Channel code="BHE" startDate="2013-02-07T21:00:00Z" endDate="2013-06-10T21:00:00Z" locationCode="60">
      <fsx:Channel code="BHE" startDate="2013-06-10T21:00:00Z" endDate="2013-10-25T23:00:00Z" locationCode="60”>

and the related validator messages read: 

CI_DSN6.xml|252|[[
        Channel [code=BHE, locationCode=60, startDate=Thu Nov 01 18:00:00 MDT 2012, endDate=Thu Feb 07 14:00:00 MST 2013],
        Channel [code=BHE, locationCode=60, startDate=Thu Feb 07 14:00:00 MST 2013, endDate=Mon Jun 10 15:00:00 MDT 2013],
        Channel [code=BHE, locationCode=60, startDate=Mon Jun 10 15:00:00 MDT 2013, endDate=Fri Oct 25 17:00:00 MDT 2013],

There seems to be a time zone issue that makes it hard to correlated the 
validator messages with the epochs in the stationXML file, but I don’t think 
that this is the real problem.  

Here is an example of channel epochs from another station that don’t trigger 
an overlap error:

      <fsx:Channel code="EHZ" startDate="1995-10-24T00:00:00Z" endDate="1996-06-12T00:00:00Z" locationCode="">
      <fsx:Channel code="EHZ" startDate="1996-06-12T00:00:00Z" endDate="2008-06-17T16:23:23Z" locationCode="">
      <fsx:Channel code="EHZ" startDate="2008-06-17T16:23:23Z" endDate="2014-03-28T18:00:00Z" locationCode="">
      <fsx:Channel code="EHZ" startDate="2014-03-28T18:00:00Z" endDate="2016-03-18T16:30:00Z" locationCode="">
      <fsx:Channel code="EHZ" startDate="2016-03-18T16:30:00Z" locationCode=“”>

I can’t spot anything in the Channel lines to explain why one is treated differently than the other.  
Neither have actual overlaps…

I’m also surprised that if the code thinks all of these SNCLs have a 252 error, that each SNCL isn’t 
getting its a SNCL-specific error message.  They’re all getting dumped together.

cheers,
Mary

**Comment by yazan-iris** [comment]
This is resolved, output message is corrected
