### ISSUE TITLE
Polynomials not being exempted from rule 413

### ISSUE THREAD

**Issue by metempleton** [iris-edu/StationXML-Validator#63]
While it looks like Polynomial stages at stage 0 _are_ correctly being exempted from rule 410, rule 
413 is incorrectly triggering for polynomial stages numbered other than 0.  Any stage (0 or otherwise) that is a polynomial will typically not have a Gain specified.  

Both rules cite restriction R1, which refers to "Response:InstrumentPolynomial at stage 0", but what is actually the case is that 
- Response:InstrumentPolynomial at stage 0 does not trigger rule 410.
- Response:StagePolynomial at stage N does not trigger rule 413 for stage N.
Does there need to be two separate restrictions?

**Comment by timronan** [comment]
In your examples, are Response:Stage[0] defined as Response:InstrumentSensitivity instead of Response:InstrumentPolynomial? If so, then that response violates the Seed manual. R1 may need to be split into two restriction but that could also make it two easier to define a Polynomial Response with a Response:InstrumentSensitivity instead of Response:InstrumentPolynomial at stage 0.

**Comment by timronan** [comment]
This issue has been addressed by Issue #69 and the Rule 415.
