### ISSUE TITLE
"No decimation found" warning... erroneous?

### ISSUE THREAD

**Issue by jpjones76** [iris-edu/stationxml-validator#78]
A channel whose response comprises a single PolesZeros stage has no Decimation node and thus throws two warnings in your validator, even with XML downloaded from IRIS.

MWE: https://service.iris.edu/fdsnws/station/1/query?net=UW&sta=VBP&cha=EHZ&level=response&format=xml&includecomments=true&nodata=404

RuleId | Network | Station | Channel | Location | StartDate | EndDate | Message
-- | -- | -- | -- | -- | -- | -- | --
420 | UW | VBP | EHZ |   | 1979-10-01T00:00:00 | 1987-10-01T00:00:00 | No decimation found
421 | UW | VBP | EHZ |   | 1979-10-01T00:00:00 | 1987-10-01T00:00:00 | Decimation cannot be null

I'm not sure Decimation is required in station XML 1.1. It has property minOccurs="0" in the schema definition.

Please clarify: is this warning being thrown correctly? Is this a special case? Is FDSNWS returning station XML that fails your validator?

Thanks.

**Comment by chad-iris** [comment]
> Please clarify: is this warning being thrown correctly? Is this a special case? Is FDSNWS returning station XML that fails your validator?

It's being thrown correctly.  Our fdsnws-station is currently returning results that will not validate.  To explain: the IRIS DMC has metadata collected over decades, some of it was not good SEED let alone StationXML.  With our transition to StationXML, we are also going to be applying more stringent rules about what we will accept.  In the mean time we will be working with contributors to fix up the already-ingested metadata that has problems, while continuing to serve that metadata (after all it's no worse that we have been serving for years).

**Comment by jpjones76** [comment]
I understand, but I feel that the implications should be spelled out explicitly in your documentation. 

I'll explain. Advance apologies for my lack of brevity.

Imposing stricter conditions on station XML than the response-level info from IRIS itself means that developers need to write additional code to compensate for data centers' shortcomings. In other words, this places the burden on us to add the "missing" information, even when rewriting fully-FDSN-compliant XML. 

There's no guarantee this will be meaningful or accurate info, though. For example, above, I can compensate by inserting an assumed decimation node in every `PolesZeros` stage, but they aren't present in this stage for any XML I've seen, including yours (IRIS'). So I'm assuming every property written (e.g. `Decimation` = 1, `InputSampleRate` = fs). Are those safe assumptions? What if another developer assumes different values?

Please, if nothing else, warn developesr that this is expected of us and add an API with what you expect for "assumed" values. Neither of these things is clear from existing documentation.

Thank you.

**Comment by jpjones76** [comment]
Addendum: this warning uses an inconsistent test condition. 

_Example_: https://service.iris.edu/fdsnws/station/1/query?net=UW&sta=VCL&level=response&format=xml&includecomments=true&nodata=404

_Inconsistency_: 
1. if a channel response has multiple stages, including a `PolesZeros` stage, a warning is thrown only if **no** stage contains a `Decimation` node. _Example_: UW.VCL..SHZ doesn't throw this warning, but `PolesZeros` (stage 1) lacks `Decimation`. `Decimation` appears only in stage 2.
2. If a channel response contains only a single `PolesZeros` stage, then the stage must include `Decimation` for the channel to validate. _Example_: UW.VCL..EHZ throws this warning and has only `PolesZeros` in the response.

It appears that an entire channel is valid if _at least one stage_ of the response contains `Decimation`. 

Is this intended?

**Comment by rcasey-iris** [comment]
Hi Joshua-

	This description is largely correct.  I think the EHZ channel you ran across for UW VCL is in fact in violation of the documented rules, so it's less inconsistency than you've highlighted an incomplete response.  The comment on this station is that the UW provided an estimated response to this very old instrument, not knowing what the true specs are.  It should still contain at minimum a 1:1 decimation entry...or as in the SHZ channel that follows, a second stage indicating the digital filter/recorder, with attendant decimation.

	-Rob

**Comment by timronan** [comment]
@jpjones76 
> It appears that an entire channel is valid if at least one stage of the response contains Decimation.

This is true and seems to be stated as such in the [validation test](http://iris-edu.github.io/stationxml-validator/tests.html) documentation under rule 420. 

> A Response must contain at least one instance of Response:Stage:Decimation. 

The forth column of the validation test documentation, Restrictions,  describes cases where validation rules do not apply. Rule 420 does not apply to channel level restriction 1, 2 and response level restriction 1. Please refer to the documentation for further details.

Rule 420 has been set as a warning, not an error, because having a single stage of only a pole and zero [Blockette 53](SEED Manual) can be valid. Please use evalresp to verify the validity of individual responses in question. We decided to leave Rule 420 as a warning so that network operators and metadata creators would be warned of potential decimation typos or inconsistencies in large stationXML documents. The validator has been designed as a user friendly tool to encourage best practices and clean metadata creation and submission. 

Thank you for reviewing the stationxml-validator, please continue to post any issues you see. I will work on updating the documentation and will discuss creating another response level restriction. Also, you maybe interested in the [stationxml-seed-converter](https://github.com/iris-edu/stationxml-seed-converter/releases/tag/2.0.5). If you use this tool, please post any issues you find. We will do our best to promptly address and/or fix any posted issues.
